# Generated by Django 5.2.12 on 2026-04-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_url',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
